### ISSUE TITLE
 Cannot read property of undefined in lib/client.js

### ISSUE THREAD

**Issue by Himanshu4** [vpulim/node-soap#625] opened 2015-04-11 15:51 UTC
We have an api which sends json embedded in soap body. We are frequently getting this error where obj is {} (empty) and obj.Body is undefined after xml conversion in lib/client.js. Seems like an issue with xml to object conversion.

Uncaught Error: Cannot read property 'ConfirmationSeatBookingSoapOut' of undefined
TypeError: Cannot read property 'ConfirmationSeatBookingSoapOut' of undefined
    at releases/source/node_modules/soap/lib/client.js:245:24
    at Request._callback (releases/source/node_modules/soap/lib/http.js:61:7)
    at Request.self.callback (/releases/source/node_modules/request/request.js:121:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (releases/source/node_modules/request/request.js:985:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (releases/source/node_modules/request/request.js:936:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20

**Comment by chaitanyagpt21** [comment] 2015-04-11 17:14
+1

**Comment by ashoksahoo** [comment] 2015-04-16 10:49
+1 I also get similar error on similar api
`TypeError: Cannot read property 'SearchResponse' of undefined`

**Comment by evanshortiss** [comment] 2015-04-16 21:03
Would be good to know the contents of the line you guys are seeing this on and a specific version.

I just found an error that sounds similar to this and it occurs due to [this line (246)](https://github.com/vpulim/node-soap/blob/master/lib/client.js#L246) in the current master. This line is 208 in my version (0.8.0)

A simple fix would be to add a try/catch or check the properties exist before calling:

```javascript
result = obj.Body[output.$name];
```

Might investigate more myself to ensure this would be sufficient.

**Comment by Himanshu4** [comment] 2015-04-26 16:26
@evanshortiss : yes, I am referring to https://github.com/vpulim/node-soap/blob/master/lib/client.js#L246 in lib/client.js. In this case, obj.Body is coming undefined.

**Comment by cubissimo** [comment] 2015-04-27 12:20
i'm facing the same problem, any clues?

**Comment by pentode** [comment] 2015-04-27 12:44
@Himanshu4 what do you mean by "json embedded in soap body"?  Do you mean

`
<soapenv:Body>
  {"foo":"bar"}
</soapenv:Body>
`

If not, could you provide a simple example that can be used to reproduce this error?

**Comment by tuananh** [comment] 2015-04-29 07:42
I have similar issue as well. Anyone knows the fix for this?

**Comment by kytwb** [comment] 2015-05-13 10:24
Just happened to me, with response's body empty.

**Comment by garvitlnmiit** [comment] 2015-05-13 12:10
+1

**Comment by arthurschreiber** [comment] 2015-05-19 09:31
Yeah, this happens if the response body is empty. The xml parser happily parses empty strings into `{}`, which then is assigned to `obj`. `obj.Body` will then be `undefined`, and trying to access any properties on it causes the aforementioned failure.

This is not fixed in master.

**Comment by skimsey** [comment] 2015-08-24 22:58
+1

**Closed** 2015-08-25 06:06 UTC
