### ISSUE TITLE
Cannot assign to read only property 'namespace' of xsd:string

### ISSUE THREAD

**Issue by PavelPolyakov** [vpulim/node-soap#550] opened 2015-01-31 19:48 UTC
Hi there,

Here is my code, which works locally with node 0.11.14:

~~~javascript
return new Promise(function (resolve, reject) {
			//resolve(false);
			if (!iban) {
				reject(new Error('IBAN must be provided'));
			}

			soap.createClient(config.url, function (err, client) {
				var args = {
					iban     : iban,
					user     : config.user,
					password : config.password
				};

				/*jshint camelcase:false*/
				client.validate_iban(args, function (err, result) {
					var blz = false;
					if (_.hasPath(result, 'return.bank_code.$value')) {
						blz = result.return.bank_code.$value;
					}
					resolve(blz);
				});
				/*jshint camelcase:true*/
			});
		});
~~~

This is my test:
~~~javascript
    it('checks correct iban', function (done) {
        ibanrechner.getBlzByIban('PL2510301944****101620901000').then(function(result){
            console(result);
            expect(1).to.equal(1);
            done();
        }).catch(function(err){
            console.log(err);
            expect(0).to.equal(1);
            done();
        });
    });
~~~

And this is what I got when this test performs on my build server:
![image](https://cloud.githubusercontent.com/assets/839290/5989503/5d84b2ec-a98a-11e4-9a21-4ceffca64fc0.png)

Could someone tell me what is wrong here?
I've tried another variant with the ```chai-as-promised``` lib, but the soap is not working on my build server.

What could be a reason of the error?

Regards,

**Comment by PavelPolyakov** [comment] 2015-02-02 17:40
I've checked, the same issue has place on 0.11.16 .

Any feedback?

**Comment by herom** [comment] 2015-02-02 21:09
Hello @PavelPolyakov - thanks a lot for filing this issue. As you might see from our [Travis CI Config File](https://github.com/vpulim/node-soap/blob/master/.travis.yml) all our test are run against `node v0.8` and `node v0.10` and we're currently not supporting `node v0.11`.

From looking at your code samples I can't tell what could be going wrong here - it would help a lot if you could track it down by debugging in `MessageElement.postProcess()`, at least.

**Comment by PavelPolyakov** [comment] 2015-02-03 14:32
Here is the state of the variables at that point:
![image](https://cloud.githubusercontent.com/assets/839290/6021931/92a95a5a-abb9-11e4-8af2-e94b73839746.png)

Anyhow, thanks for the client, hope soon you would support the node 0.11 as well :)
I'm new to node, so it's hard to say for me which change from 0.11.14 to 0.11.15 could bring this issue on the table.

Currently I do not need any deep SOAP integration, so I would just emulate the SOAP POST query with request.

**Comment by asafyish** [comment] 2015-02-04 12:46
It also happens on iojs 1.0.4 and 1.1.0.

**Comment by jfroffice** [comment] 2015-02-08 21:30
+1

on node v0.12.0

**Comment by herom** [comment] 2015-02-09 10:03
Likely this is also relate to #555 - @timmckenzie did some research and found a possible related bug in the `request` library `node-soap` is using.

**Comment by andrewbranch** [comment] 2015-02-12 01:18
This seems to be caused by newer versions of node/iojs enforcing JavaScript strict mode: you can’t declare properties of primitives. I can’t actually find documentation that says that’s a rule exactly, but Node definitely thinks it is.

[Here](https://github.com/vpulim/node-soap/blob/master/lib/wsdl.js#L872), you are assigning to a property of `elem`. It looks like `elem` is usually an object, but sometimes it’s a string primitive, like when the description comes from [here](https://github.com/vpulim/node-soap/blob/master/lib/wsdl.js#L735). The viable solutions are:
 1. Turn off strict mode in `wsdl.js`
 2. Refactor the element descriptions such that they always return an object

**Comment by andrewbranch** [comment] 2015-02-12 23:46
If you try to assign properties to a primitive when you're not in strict mode, nothing happens:

```javascript
var primitive = 'foo';
primitive.prop = true;
primitive.prop; // undefined
```

So I propose just to wrap the offending lines in `if (typeof elem !== 'string')`. Any issues with that? PR to follow.

**Closed** 2015-02-17 19:57 UTC
